export const movie = {
  adult: false,
  backdrop_path: "/zxnfMi4qW0bdAtcwCogrR9dRrqd.jpg",
  genre_ids: [878, 9648, 53],
  id: 1103825,
  original_language: "en",
  original_title: "War of the Worlds: The Attack",
  overview:
    "Three young astronomers fight to survive a deadly Martian invasion.",
  popularity: 379.327,
  poster_path: "/c3CUKHtQUvPvp9NSFsKwYsPLAdW.jpg",
  release_date: "2023-04-21",
  title: "War of the Worlds: The Attack",
  video: false,
  vote_average: 5.389,
  vote_count: 104,
};

export const trendingMovies = [
  {
    adult: false,
    backdrop_path: "/zxnfMi4qW0bdAtcwCogrR9dRrqd.jpg",
    genre_ids: [878, 9648, 53],
    id: 1103825,
    original_language: "en",
    original_title: "War of the Worlds: The Attack",
    overview:
      "Three young astronomers fight to survive a deadly Martian invasion.",
    popularity: 379.327,
    poster_path: "/c3CUKHtQUvPvp9NSFsKwYsPLAdW.jpg",
    release_date: "2023-04-21",
    title: "War of the Worlds: The Attack",
    video: false,
    vote_average: 5.389,
    vote_count: 104,
  },
];

export const recommendMovies = [
  ...trendingMovies,
  {
    adult: false,
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 2690.543,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.458,
    vote_count: 3616,
  },
  {
    adult: false,
    backdrop_path: "/zh614Bixv2ePaHK8gzcUpUmcvYv.jpg",
    genre_ids: [53, 28, 80],
    id: 1102776,
    original_language: "fr",
    original_title: "AKA",
    overview:
      "A steely special ops agent finds his morality put to the test when he infiltrates a crime syndicate and unexpectedly bonds with the boss' young son.",
    popularity: 127.777,
    poster_path: "/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg",
    release_date: "2023-04-28",
    title: "AKA",
    video: false,
    vote_average: 6.972,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: "/xnAi4BRoO3ZQ3wwxGn6UNoxQzDq.jpg",
    genre_ids: [80, 28],
    id: 823999,
    original_language: "it",
    original_title: "Diabolik - Ginko all'attacco!",
    overview:
      "Diabolik nearly gets caught in Inspector Ginko's latest trap, leaving his partner in crime Eva Kant behind in the escape. Furious, Eva offers Ginko her help in capturing the King of Terror, but the former has to face the return of an old flame of his.",
    popularity: 57.562,
    poster_path: "/8QVbWBv94BAT9u1q9uJccwOxMzt.jpg",
    release_date: "2022-11-17",
    title: "Diabolik - Ginko Attacks",
    video: false,
    vote_average: 6.057,
    vote_count: 357,
  },
  {
    adult: false,
    backdrop_path: "/2UBspLYMarpT0YDgymFBswOXwwk.jpg",
    genre_ids: [16, 10751],
    id: 893366,
    original_language: "fr",
    original_title:
      "Le petit Nicolas - Qu'est-ce qu'on attend pour être heureux ?",
    overview:
      "Somewhere between Montmartre and Saint-Germain-des-Prés, Jean-Jacques Sempé and René Goscinny lean over a large white sheet of paper and bring to life a mischievous and endearing boy, Little Nicolas. From schoolyard games and fights to summer camp pranks and camaraderie, Nicolas lives a merry and enriching childhood – and brings friendship and newfound life to his creators, too.",
    popularity: 150.84,
    poster_path: "/yTsaoXtBndypAQJj5C16d3Zmfxf.jpg",
    release_date: "2022-10-12",
    title: "Little Nicholas: Happy As Can Be",
    video: false,
    vote_average: 6.508,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: "/2X5nnvkWvYRFmTspXY7lsJqDzog.jpg",
    genre_ids: [10749, 18, 35],
    id: 988078,
    original_language: "es",
    original_title: "A través del mar",
    overview:
      "After a year of long-distance, Raquel and Ares reunite on a steamy beach trip. Faced with fresh flirtations and insecurities, will their love prevail?",
    popularity: 135.686,
    poster_path: "/dAyJqJ8KoglZysttC6BfVmDFQUt.jpg",
    release_date: "2023-06-23",
    title: "Through My Window: Across the Sea",
    video: false,
    vote_average: 6.613,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: "/uJAR8HJCNgedmgMz0G8EzGCoZAE.jpg",
    genre_ids: [35, 10749],
    id: 1098239,
    original_language: "es",
    original_title: "Tangos, tequilas, y algunas mentiras",
    overview:
      "Lu has a perfect life. Or so she pretends to have. She meets the handsome, short-tempered Argentinian, Diego, who is on a visit to Mexico, and she is confident to get him head over heels in love with her. In order to win a wager with her friends, her life will take a turn when she does the impossible to win him over, including taking a trip to Argentina to look for him.",
    popularity: 17.678,
    poster_path: "/o9S6GW9MGyQZpRpPj65k0RIqYNL.jpg",
    release_date: "2023-03-09",
    title: "Tango, Tequila and Some Lies",
    video: false,
    vote_average: 7.1,
    vote_count: 90,
  },

  {
    adult: false,
    backdrop_path: "/msBuBppEFq3QvaRsJYz0r595gC5.jpg",
    genre_ids: [12],
    id: 1059638,
    original_language: "pl",
    original_title: "Pan Samochodzik i templariusze",
    overview:
      "A well-known art historian, treasure hunter and owner of an unusual car stumbles upon a Templar treasure, which is the key to a great power that can upset the balance of good and evil in the world. Supported by friendly scouts, Mr. Car starts a big race against time and a hostile organization, the stake of which is the heritage of knightly orders.",
    popularity: 342.828,
    poster_path: "/xEAXVe0BzW4K9Ky6eTo4CJwzJ8P.jpg",
    release_date: "2023-07-12",
    title: "Mr. Car and the Knights Templar",
    video: false,
    vote_average: 6.29,
    vote_count: 100,
  },
  {
    adult: false,
    backdrop_path: "/sil4GzTAvmxFWqsp5FWZcG7adtS.jpg",
    genre_ids: [80],
    id: 1074262,
    original_language: "tr",
    original_title: "Kötü Adamın 10 Günü",
    overview:
      "Battered, broken and bereaved, a private investigator must muscle his way through a tangle of lies to uncover the truth behind a mansion murder.",
    popularity: 145.248,
    poster_path: "/woY4fKio0ypWqj2uQj96tCiCRXV.jpg",
    release_date: "2023-08-18",
    title: "10 Days of a Bad Man",
    video: false,
    vote_average: 6.818,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/mV1HOCbUqx7nfFPwledYsvMYHrw.jpg",
    genre_ids: [28, 53],
    id: 47964,
    original_language: "en",
    original_title: "A Good Day to Die Hard",
    overview:
      "Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.",
    popularity: 292.649,
    poster_path: "/evxtv4e8Amm436Y5rW16RkGu8pX.jpg",
    release_date: "2013-02-06",
    title: "A Good Day to Die Hard",
    video: false,
    vote_average: 5.313,
    vote_count: 5998,
  },
  {
    adult: false,
    backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 489.514,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.665,
    vote_count: 9515,
  },
  {
    adult: false,
    backdrop_path: "/daeD5T4MxFk5MppZlaNZoaK6lE9.jpg",
    genre_ids: [16, 14],
    id: 811948,
    original_language: "ja",
    original_title: "鬼滅の刃 柱合会議・蝶屋敷編",
    overview:
      "Tanjiro and his sister Nezuko have been apprehended by the Demon Slayer Hashira, a group of extremely skilled swordfighters. Tanjiro undergoes trial for violating the Demon Slayer code, specifically smuggling Nezuko, a Demon, onto Mt. Natagumo. A recap film of Kimetsu no Yaiba, covering episodes 22-26 with some new footage and special ending credits.",
    popularity: 124.757,
    poster_path: "/iTmJwZxGHYAk5EiVc68UvZTMSuP.jpg",
    release_date: "2021-04-15",
    title: "Demon Slayer: Kimetsu no Yaiba the Hashira Meeting Arc",
    video: true,
    vote_average: 7.116,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: "/ltpW5exyTdqL5twV8zRMajf1VgU.jpg",
    genre_ids: [99],
    id: 24791,
    original_language: "ja",
    original_title: "A",
    overview:
      "Roughly chronological, from 3/96 to 11/96, with a coda in spring of 1997: inside compounds of Aum Shinrikyo, a Buddhist sect led by Shoko Asahara. (Members confessed to a murderous sarin attack in the Tokyo subway in 1995.) We see what they eat, where they sleep, and how they respond to media scrutiny, on-going trials, the shrinking of their fortunes, and the criticism of society. Central focus is placed on Hiroshi Araki, a young man who finds himself elevated to chief spokesman for Aum after its leaders are arrested. Araki faces extreme hostility from the Japanese public, who find it hard to believe that most followers of the cult had no idea of the attacks and even harder to understand why these followers remain devoted to the religion, if not the violence.",
    popularity: 1.484,
    poster_path: "/dBLzrfh5DtxJey1hOYZaN2drPe3.jpg",
    release_date: "1998-09-09",
    title: "A",
    video: false,
    vote_average: 6.076,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/OJLBXOSq80PwTu9jTwSEz9yDHC.jpg",
    genre_ids: [28, 12, 36, 18],
    id: 796185,
    original_language: "fr",
    original_title: "Les Trois Mousquetaires : D'Artagnan",
    overview:
      "D'Artagnan, a spirited young Gascon, is left for dead after trying to save a noblewoman from being kidnapped. Once in Paris, he tries by all means to find his attackers, unaware that his quest will lead him to the very heart of a war where the future of France is at stake. Aided by King's Musketeers Athos, Porthos and Aramis, he faces the machinations of villainous Cardinal Richelieu and Milady de Winter, while falling in love with Constance, the Queen's confidante.",
    popularity: 136.706,
    poster_path: "/wve9qIZ8pXrDpHy1h47cGXHjZpH.jpg",
    release_date: "2023-04-05",
    title: "The Three Musketeers: D'Artagnan",
    video: false,
    vote_average: 7.25,
    vote_count: 570,
  },
  {
    adult: false,
    backdrop_path: "/1Ju8s25F6l1K1cQRU2mHaODQvzj.jpg",
    genre_ids: [28, 12, 10752],
    id: 961420,
    original_language: "ja",
    original_title: "キングダム2 遥かなる大地へ",
    overview:
      "It follows a young man who dreams of becoming a general and Ying Zheng, whose goal is unification.",
    popularity: 406.029,
    poster_path: "/wE4NqJosSPjiyqStBEv67mQbR1b.jpg",
    release_date: "2022-07-15",
    title: "Kingdom 2: Far and Away",
    video: false,
    vote_average: 6.85,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/zcySy6dnSmyqiichtDgO7AEeZoq.jpg",
    genre_ids: [28, 18, 53],
    id: 254128,
    original_language: "en",
    original_title: "San Andreas",
    overview:
      "In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.",
    popularity: 466.695,
    poster_path: "/2Gfjn962aaFSD6eST6QU3oLDZTo.jpg",
    release_date: "2015-05-27",
    title: "San Andreas",
    video: false,
    vote_average: 6.23,
    vote_count: 7941,
  },
  {
    adult: false,
    backdrop_path: "/qdFrqXYH6PtyAVlegub7bpoSgro.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 573171,
    original_language: "es",
    original_title: "Huevitos Congelados",
    overview:
      "Follow the adventures of Toto and his family, who will have to travel to the South Pole to fulfill their promise to return a polar bear and some Spanish penguins to their home. In order to fulfill the promise, they will have to overcome some obstacles that will teach them how important teamwork is.",
    popularity: 88.718,
    poster_path: "/d7i9UXE7IfPx2uYtYKzgjs6zYzR.jpg",
    release_date: "2022-12-14",
    title: "A Frozen Rooster",
    video: false,
    vote_average: 7.68,
    vote_count: 314,
  },
  {
    adult: false,
    backdrop_path: "/a2K8ak4pGCHR3O0hMualcokXXpa.jpg",
    genre_ids: [10749, 53],
    id: 210763,
    original_language: "kn",
    original_title: "A",
    overview:
      "A film director fades away from the industry after the failed love with the heroine of his movie. After being rehabilitated, he learns that some people conspired his fall and decides to take revenge.",
    popularity: 1.07,
    poster_path: "/y3DH68oWOGMZ637tqYHfTGU4Bif.jpg",
    release_date: "1998-02-12",
    title: "A",
    video: false,
    vote_average: 6.069,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: "/uXADu1mfgTwNkBjgtDkLQRt5N8a.jpg",
    genre_ids: [99],
    id: 1094266,
    original_language: "es",
    original_title: "Amén: Francisco responde",
    overview:
      "Ten young people from all over the world meet in Rome with Pope Francis with the aim of talking and conveying to him the main concerns of their generation. What awaits them is an unprecedented meeting, a face-to-face conversation, and a unique event.",
    popularity: 10.366,
    poster_path: "/dqyzHNor7wEYhWRzVRrEuvqbCkU.jpg",
    release_date: "2023-04-05",
    title: "The Pope: Answers",
    video: false,
    vote_average: 7.696,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/ujL5e6S2PSkPE3FNSNrPGlB2haF.jpg",
    genre_ids: [878, 53],
    id: 919873,
    original_language: "en",
    original_title: "Arctic Void",
    overview:
      "When the power mysteriously fails, and almost everyone vanishes from a small tourist vessel in the Arctic, fear becomes the master for the three who remain. Forced ashore, the men deteriorate in body and mind until a dark truth emerges that compels them to ally or perish.",
    popularity: 10.682,
    poster_path: "/2OkdcVn1wIgRA4zo8tTbn7NNDUT.jpg",
    release_date: "2022-01-14",
    title: "Arctic Void",
    video: false,
    vote_average: 4.935,
    vote_count: 31,
  },
];

export const genres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];
