export const movie = {
  adult: false,
  backdrop_path: "/zxnfMi4qW0bdAtcwCogrR9dRrqd.jpg",
  genre_ids: [878, 9648, 53],
  id: 1103825,
  original_language: "en",
  original_title: "War of the Worlds: The Attack",
  overview:
    "Three young astronomers fight to survive a deadly Martian invasion.",
  popularity: 379.327,
  poster_path: "/c3CUKHtQUvPvp9NSFsKwYsPLAdW.jpg",
  release_date: "2023-04-21",
  title: "War of the Worlds: The Attack",
  video: false,
  vote_average: 5.389,
  vote_count: 104,
};

export const trendingMovies = [
  {
    adult: false,
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 2690.543,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.458,
    vote_count: 3616,
  },
  {
    adult: false,
    backdrop_path: "/zh614Bixv2ePaHK8gzcUpUmcvYv.jpg",
    genre_ids: [53, 28, 80],
    id: 1102776,
    original_language: "fr",
    original_title: "AKA",
    overview:
      "A steely special ops agent finds his morality put to the test when he infiltrates a crime syndicate and unexpectedly bonds with the boss' young son.",
    popularity: 127.777,
    poster_path: "/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg",
    release_date: "2023-04-28",
    title: "AKA",
    video: false,
    vote_average: 6.972,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: "/xnAi4BRoO3ZQ3wwxGn6UNoxQzDq.jpg",
    genre_ids: [80, 28],
    id: 823999,
    original_language: "it",
    original_title: "Diabolik - Ginko all'attacco!",
    overview:
      "Diabolik nearly gets caught in Inspector Ginko's latest trap, leaving his partner in crime Eva Kant behind in the escape. Furious, Eva offers Ginko her help in capturing the King of Terror, but the former has to face the return of an old flame of his.",
    popularity: 57.562,
    poster_path: "/8QVbWBv94BAT9u1q9uJccwOxMzt.jpg",
    release_date: "2022-11-17",
    title: "Diabolik - Ginko Attacks",
    video: false,
    vote_average: 6.057,
    vote_count: 357,
  },
];

export const recommendMovies = [
  ...trendingMovies,

  {
    adult: false,
    backdrop_path: "/2UBspLYMarpT0YDgymFBswOXwwk.jpg",
    genre_ids: [16, 10751],
    id: 893366,
    original_language: "fr",
    original_title:
      "Le petit Nicolas - Qu'est-ce qu'on attend pour être heureux ?",
    overview:
      "Somewhere between Montmartre and Saint-Germain-des-Prés, Jean-Jacques Sempé and René Goscinny lean over a large white sheet of paper and bring to life a mischievous and endearing boy, Little Nicolas. From schoolyard games and fights to summer camp pranks and camaraderie, Nicolas lives a merry and enriching childhood – and brings friendship and newfound life to his creators, too.",
    popularity: 150.84,
    poster_path: "/yTsaoXtBndypAQJj5C16d3Zmfxf.jpg",
    release_date: "2022-10-12",
    title: "Little Nicholas: Happy As Can Be",
    video: false,
    vote_average: 6.508,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: "/2X5nnvkWvYRFmTspXY7lsJqDzog.jpg",
    genre_ids: [10749, 18, 35],
    id: 988078,
    original_language: "es",
    original_title: "A través del mar",
    overview:
      "After a year of long-distance, Raquel and Ares reunite on a steamy beach trip. Faced with fresh flirtations and insecurities, will their love prevail?",
    popularity: 135.686,
    poster_path: "/dAyJqJ8KoglZysttC6BfVmDFQUt.jpg",
    release_date: "2023-06-23",
    title: "Through My Window: Across the Sea",
    video: false,
    vote_average: 6.613,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: "/uJAR8HJCNgedmgMz0G8EzGCoZAE.jpg",
    genre_ids: [35, 10749],
    id: 1098239,
    original_language: "es",
    original_title: "Tangos, tequilas, y algunas mentiras",
    overview:
      "Lu has a perfect life. Or so she pretends to have. She meets the handsome, short-tempered Argentinian, Diego, who is on a visit to Mexico, and she is confident to get him head over heels in love with her. In order to win a wager with her friends, her life will take a turn when she does the impossible to win him over, including taking a trip to Argentina to look for him.",
    popularity: 17.678,
    poster_path: "/o9S6GW9MGyQZpRpPj65k0RIqYNL.jpg",
    release_date: "2023-03-09",
    title: "Tango, Tequila and Some Lies",
    video: false,
    vote_average: 7.1,
    vote_count: 90,
  },

  {
    adult: false,
    backdrop_path: "/msBuBppEFq3QvaRsJYz0r595gC5.jpg",
    genre_ids: [12],
    id: 1059638,
    original_language: "pl",
    original_title: "Pan Samochodzik i templariusze",
    overview:
      "A well-known art historian, treasure hunter and owner of an unusual car stumbles upon a Templar treasure, which is the key to a great power that can upset the balance of good and evil in the world. Supported by friendly scouts, Mr. Car starts a big race against time and a hostile organization, the stake of which is the heritage of knightly orders.",
    popularity: 342.828,
    poster_path: "/xEAXVe0BzW4K9Ky6eTo4CJwzJ8P.jpg",
    release_date: "2023-07-12",
    title: "Mr. Car and the Knights Templar",
    video: false,
    vote_average: 6.29,
    vote_count: 100,
  },
  {
    adult: false,
    backdrop_path: "/sil4GzTAvmxFWqsp5FWZcG7adtS.jpg",
    genre_ids: [80],
    id: 1074262,
    original_language: "tr",
    original_title: "Kötü Adamın 10 Günü",
    overview:
      "Battered, broken and bereaved, a private investigator must muscle his way through a tangle of lies to uncover the truth behind a mansion murder.",
    popularity: 145.248,
    poster_path: "/woY4fKio0ypWqj2uQj96tCiCRXV.jpg",
    release_date: "2023-08-18",
    title: "10 Days of a Bad Man",
    video: false,
    vote_average: 6.818,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/mV1HOCbUqx7nfFPwledYsvMYHrw.jpg",
    genre_ids: [28, 53],
    id: 47964,
    original_language: "en",
    original_title: "A Good Day to Die Hard",
    overview:
      "Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.",
    popularity: 292.649,
    poster_path: "/evxtv4e8Amm436Y5rW16RkGu8pX.jpg",
    release_date: "2013-02-06",
    title: "A Good Day to Die Hard",
    video: false,
    vote_average: 5.313,
    vote_count: 5998,
  },
  {
    adult: false,
    backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 489.514,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.665,
    vote_count: 9515,
  },
  {
    adult: false,
    backdrop_path: "/daeD5T4MxFk5MppZlaNZoaK6lE9.jpg",
    genre_ids: [16, 14],
    id: 811948,
    original_language: "ja",
    original_title: "鬼滅の刃 柱合会議・蝶屋敷編",
    overview:
      "Tanjiro and his sister Nezuko have been apprehended by the Demon Slayer Hashira, a group of extremely skilled swordfighters. Tanjiro undergoes trial for violating the Demon Slayer code, specifically smuggling Nezuko, a Demon, onto Mt. Natagumo. A recap film of Kimetsu no Yaiba, covering episodes 22-26 with some new footage and special ending credits.",
    popularity: 124.757,
    poster_path: "/iTmJwZxGHYAk5EiVc68UvZTMSuP.jpg",
    release_date: "2021-04-15",
    title: "Demon Slayer: Kimetsu no Yaiba the Hashira Meeting Arc",
    video: true,
    vote_average: 7.116,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: "/ltpW5exyTdqL5twV8zRMajf1VgU.jpg",
    genre_ids: [99],
    id: 24791,
    original_language: "ja",
    original_title: "A",
    overview:
      "Roughly chronological, from 3/96 to 11/96, with a coda in spring of 1997: inside compounds of Aum Shinrikyo, a Buddhist sect led by Shoko Asahara. (Members confessed to a murderous sarin attack in the Tokyo subway in 1995.) We see what they eat, where they sleep, and how they respond to media scrutiny, on-going trials, the shrinking of their fortunes, and the criticism of society. Central focus is placed on Hiroshi Araki, a young man who finds himself elevated to chief spokesman for Aum after its leaders are arrested. Araki faces extreme hostility from the Japanese public, who find it hard to believe that most followers of the cult had no idea of the attacks and even harder to understand why these followers remain devoted to the religion, if not the violence.",
    popularity: 1.484,
    poster_path: "/dBLzrfh5DtxJey1hOYZaN2drPe3.jpg",
    release_date: "1998-09-09",
    title: "A",
    video: false,
    vote_average: 6.076,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/OJLBXOSq80PwTu9jTwSEz9yDHC.jpg",
    genre_ids: [28, 12, 36, 18],
    id: 796185,
    original_language: "fr",
    original_title: "Les Trois Mousquetaires : D'Artagnan",
    overview:
      "D'Artagnan, a spirited young Gascon, is left for dead after trying to save a noblewoman from being kidnapped. Once in Paris, he tries by all means to find his attackers, unaware that his quest will lead him to the very heart of a war where the future of France is at stake. Aided by King's Musketeers Athos, Porthos and Aramis, he faces the machinations of villainous Cardinal Richelieu and Milady de Winter, while falling in love with Constance, the Queen's confidante.",
    popularity: 136.706,
    poster_path: "/wve9qIZ8pXrDpHy1h47cGXHjZpH.jpg",
    release_date: "2023-04-05",
    title: "The Three Musketeers: D'Artagnan",
    video: false,
    vote_average: 7.25,
    vote_count: 570,
  },
  {
    adult: false,
    backdrop_path: "/1Ju8s25F6l1K1cQRU2mHaODQvzj.jpg",
    genre_ids: [28, 12, 10752],
    id: 961420,
    original_language: "ja",
    original_title: "キングダム2 遥かなる大地へ",
    overview:
      "It follows a young man who dreams of becoming a general and Ying Zheng, whose goal is unification.",
    popularity: 406.029,
    poster_path: "/wE4NqJosSPjiyqStBEv67mQbR1b.jpg",
    release_date: "2022-07-15",
    title: "Kingdom 2: Far and Away",
    video: false,
    vote_average: 6.85,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/zcySy6dnSmyqiichtDgO7AEeZoq.jpg",
    genre_ids: [28, 18, 53],
    id: 254128,
    original_language: "en",
    original_title: "San Andreas",
    overview:
      "In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.",
    popularity: 466.695,
    poster_path: "/2Gfjn962aaFSD6eST6QU3oLDZTo.jpg",
    release_date: "2015-05-27",
    title: "San Andreas",
    video: false,
    vote_average: 6.23,
    vote_count: 7941,
  },
  {
    adult: false,
    backdrop_path: "/qdFrqXYH6PtyAVlegub7bpoSgro.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 573171,
    original_language: "es",
    original_title: "Huevitos Congelados",
    overview:
      "Follow the adventures of Toto and his family, who will have to travel to the South Pole to fulfill their promise to return a polar bear and some Spanish penguins to their home. In order to fulfill the promise, they will have to overcome some obstacles that will teach them how important teamwork is.",
    popularity: 88.718,
    poster_path: "/d7i9UXE7IfPx2uYtYKzgjs6zYzR.jpg",
    release_date: "2022-12-14",
    title: "A Frozen Rooster",
    video: false,
    vote_average: 7.68,
    vote_count: 314,
  },
  {
    adult: false,
    backdrop_path: "/a2K8ak4pGCHR3O0hMualcokXXpa.jpg",
    genre_ids: [10749, 53],
    id: 210763,
    original_language: "kn",
    original_title: "A",
    overview:
      "A film director fades away from the industry after the failed love with the heroine of his movie. After being rehabilitated, he learns that some people conspired his fall and decides to take revenge.",
    popularity: 1.07,
    poster_path: "/y3DH68oWOGMZ637tqYHfTGU4Bif.jpg",
    release_date: "1998-02-12",
    title: "A",
    video: false,
    vote_average: 6.069,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: "/uXADu1mfgTwNkBjgtDkLQRt5N8a.jpg",
    genre_ids: [99],
    id: 1094266,
    original_language: "es",
    original_title: "Amén: Francisco responde",
    overview:
      "Ten young people from all over the world meet in Rome with Pope Francis with the aim of talking and conveying to him the main concerns of their generation. What awaits them is an unprecedented meeting, a face-to-face conversation, and a unique event.",
    popularity: 10.366,
    poster_path: "/dqyzHNor7wEYhWRzVRrEuvqbCkU.jpg",
    release_date: "2023-04-05",
    title: "The Pope: Answers",
    video: false,
    vote_average: 7.696,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/ujL5e6S2PSkPE3FNSNrPGlB2haF.jpg",
    genre_ids: [878, 53],
    id: 919873,
    original_language: "en",
    original_title: "Arctic Void",
    overview:
      "When the power mysteriously fails, and almost everyone vanishes from a small tourist vessel in the Arctic, fear becomes the master for the three who remain. Forced ashore, the men deteriorate in body and mind until a dark truth emerges that compels them to ally or perish.",
    popularity: 10.682,
    poster_path: "/2OkdcVn1wIgRA4zo8tTbn7NNDUT.jpg",
    release_date: "2022-01-14",
    title: "Arctic Void",
    video: false,
    vote_average: 4.935,
    vote_count: 31,
  },
];

export const genres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];

export const allMovies = [
  {
    adult: false,
    backdrop_path: "/nHWr40LGgyxymEhZCOA2WHATPpn.jpg",
    genre_ids: [28, 53, 80],
    id: 800345,
    original_language: "ko",
    original_title: "카터",
    overview:
      "Carter, who awakens two months into a deadly pandemic originating from the DMZ that has already devastated US and North Korea. He who has no recollections of his past finds a mysterious device in his head, and a lethal bomb in his mouth. A voice in his ears gives him orders to avoid getting killed and he's thrown into a mysterious operation while the CIA and North Korean coup chase him close.",
    popularity: 66.708,
    poster_path: "/uzAh3Ub2YttCz13cnyB9PvhpmIL.jpg",
    release_date: "2022-08-05",
    title: "Carter",
    video: false,
    vote_average: 6.125,
    vote_count: 307,
  },
  {
    adult: false,
    backdrop_path: "/m6h0Oj5FeqJQbQcK4xDXdD1dnMN.jpg",
    genre_ids: [10402],
    id: 874960,
    original_language: "ja",
    original_title: "「鬼滅の刃」オーケストラコンサート~鬼滅の奏~",
    overview:
      "The orchestra concert of the TV Anime Demon Slayer: Kimetsu no Yaiba is a live performance on the various music used in the anime. Clips from the anime will be shown on a screen, allowing one to enjoy the world of the work.",
    popularity: 5.812,
    poster_path: "/9QGk4EjyQIyJOeKVl6oWT2eGY4a.jpg",
    release_date: "2021-11-26",
    title: "Kimetsu Orchestra Concert",
    video: false,
    vote_average: 8.1,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: "/n7xBD3H8FC74K6bKDFIrMKFMd3h.jpg",
    genre_ids: [35],
    id: 1145041,
    original_language: "es",
    original_title: "Sueños y pan",
    overview:
      "Javi and Dani go around the city trying to sell a stolen painting.",
    popularity: 20.259,
    poster_path: "/vW1ayuyRIuIm3UhC3XxPenaVbv2.jpg",
    release_date: "2023-07-25",
    title: "Dreams and Crumbs",
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/o4IjYTVjfg89bG3oJqUnURp7MgW.jpg",
    genre_ids: [18, 10749],
    id: 73134,
    original_language: "fr",
    original_title: "Tendres Cousines",
    overview:
      "Teenage Julien loves his teenage cousin Julia among flowers in summer of '39 France.",
    popularity: 25.906,
    poster_path: "/jITSqc5btIXBRsiZbC3RkZaoY4U.jpg",
    release_date: "1980-11-19",
    title: "Tender Cousins",
    video: false,
    vote_average: 5.77,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27],
    id: 64530,
    original_language: "cn",
    original_title: "玉女聊齋",
    overview:
      "Chu is a lowly debt collector for the local strongman Wang. Problem is that Chu is too nice/honest/dopey to be very good at the grubby collections job. Chu is treated badly by his boss Wang. Eventually Wang catches one of his twin daughters in the act of seducing the hapless bumpkin Chu. Wang naturally blames Chu rather than the daughter. For punishment Wang sends Chu on an impossible quest to Satan's Temple to steal a statue of Judge Lu.",
    popularity: 11.849,
    poster_path: "/m6y5exiIeJz5L8G5nWdaimdBn3d.jpg",
    release_date: "1998-06-12",
    title: "Chinese Erotic Ghost Story",
    video: false,
    vote_average: 6.125,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/v8Rg963ryBoP3ECo8g8OK8QQ1CE.jpg",
    genre_ids: [35],
    id: 791333,
    original_language: "es",
    original_title: "El cuarto pasajero",
    overview:
      "Julián, a divorced man with financial problems, uses a cell phone application to share his car with strangers.",
    popularity: 23.042,
    poster_path: "/deOu3LDIbWtipp8vjCaszKz22LZ.jpg",
    release_date: "2022-10-28",
    title: "Four's a Crowd",
    video: false,
    vote_average: 6.481,
    vote_count: 79,
  },
  {
    adult: false,
    backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 33.318,
    poster_path: "/rf99GAg2zHKFj79QKn8ed8iPCVF.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.456,
    vote_count: 3898,
  },
  {
    adult: false,
    backdrop_path: "/rL1agLvoquKFIsPlXaMpD7XW9wH.jpg",
    genre_ids: [12, 18, 27],
    id: 28676,
    original_language: "it",
    original_title: "Schiave bianche: violenza in Amazzonia",
    overview:
      "A young woman seeks vengeance and finds love when her parents are killed in the Amazon and she is taken prisoner by an indigenous tribe of headhunters.",
    popularity: 66.637,
    poster_path: "/bvRjoKZkHgZxP7I9QY45Gw8M5hE.jpg",
    release_date: "1985-08-09",
    title: "Amazonia: The Catherine Miles Story",
    video: false,
    vote_average: 6.125,
    vote_count: 144,
  },
  {
    adult: false,
    backdrop_path: "/y0sXAOehV5zx1E64HBSyjDSZK22.jpg",
    genre_ids: [12, 18, 36],
    id: 11362,
    original_language: "en",
    original_title: "The Count of Monte Cristo",
    overview:
      "Edmond Dantés's life and plans to marry the beautiful Mercedes are shattered when his best friend, Fernand, deceives him. After spending 13 miserable years in prison, Dantés escapes with the help of a fellow inmate and plots his revenge, cleverly insinuating himself into the French nobility.",
    popularity: 33.295,
    poster_path: "/ifMgDAUXVQLY4DeOu3VTTi55jSP.jpg",
    release_date: "2002-01-23",
    title: "The Count of Monte Cristo",
    video: false,
    vote_average: 7.6,
    vote_count: 1582,
  },
  {
    adult: false,
    backdrop_path: "/7GmQKKAB3q3xkpxt1VFt2DrfviW.jpg",
    genre_ids: [53, 80],
    id: 934287,
    original_language: "da",
    original_title: "Klienten",
    overview:
      "Renowned psychologist Susanne (Signe Egholm Olsen) is caught in a living nightmare when her new client (Anton Hjejle) turns out to be a wanted serial killer.",
    popularity: 37.524,
    poster_path: "/oUhZzMpHAMgdRgLbsvBIqhY7fKe.jpg",
    release_date: "2022-06-20",
    title: "The Last Client",
    video: false,
    vote_average: 7.283,
    vote_count: 99,
  },
  {
    adult: false,
    backdrop_path: "/pl7RtZ9BmcPdXDVAPvTWa15fMbh.jpg",
    genre_ids: [53],
    id: 1076605,
    original_language: "es",
    original_title: "Cazadora",
    overview:
      "In a dystopian future, a mother and her teenage son go hunting in the mountains and encounter a stranger who threatens to upend their relationship.",
    popularity: 61.922,
    poster_path: "/8QxCd3pSSrj6QqaG4fkNkaJmUa.jpg",
    release_date: "2023-01-19",
    title: "Cazadora",
    video: false,
    vote_average: 6.1,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/sCJhnM4NI6UgEei0bwm5C6Jqz7c.jpg",
    genre_ids: [35, 18, 10749],
    id: 32516,
    original_language: "cn",
    original_title: "金瓶梅2 愛的奴隸",
    overview:
      "Rich and powerful Simon Qing has been schooled in the ways of sex by his virile father, but is still a virgin. That is, until he meets his first love Violetta who has fun with him all over his father’s estate. Their love does not last, so Simon embarks on a journey. Along the way he meets the comely nun Moon whom Simon deflowers and then marries. He then becomes enamored of Golden Lotus but she is married to dwarf Wu Da-Lang.",
    popularity: 54.809,
    poster_path: "/A1yymig7S0FTWv9cTtOwdI1cH5V.jpg",
    release_date: "2009-03-04",
    title: "The Forbidden Legend: Sex & Chopsticks 2",
    video: false,
    vote_average: 6.2,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/3EK5VCwVa4LbuuS8C1QoXaNaN3J.jpg",
    genre_ids: [14, 878, 12],
    id: 902,
    original_language: "fr",
    original_title: "La Cité des Enfants Perdus",
    overview:
      "A scientist in a surrealist society kidnaps children to steal their dreams, hoping that they slow his aging process.",
    popularity: 17.422,
    poster_path: "/whwT3Q9JxbAYzEc3t7uYYcCbTMf.jpg",
    release_date: "1995-05-17",
    title: "The City of Lost Children",
    video: false,
    vote_average: 7.293,
    vote_count: 953,
  },
  {
    adult: false,
    backdrop_path: "/12vXoZKGk1Ds7zeCLl5RpzYi3Q9.jpg",
    genre_ids: [16, 28, 12, 18, 9648],
    id: 843267,
    original_language: "ja",
    original_title: "プリンセス・プリンシパル Crown Handler 第2章",
    overview: "The second out of six movie sequels to the TV series.",
    popularity: 22.234,
    poster_path: "/bigcS5uX9bAPeMQcPUWMDUxgaxk.jpg",
    release_date: "2021-09-23",
    title: "Princess Principal Crown Handler: Chapter 2",
    video: false,
    vote_average: 7.8,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1151600,
    original_language: "ms",
    original_title: "C",
    overview: "",
    popularity: 0.6,
    poster_path: "/de94J6PyTe0CFf27saqBQcF7Itn.jpg",
    release_date: "",
    title: "C",
    video: false,
    vote_average: 8,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/ifGs4hSnqTCFmhJqCGe5Ec0cTe5.jpg",
    genre_ids: [99],
    id: 1025169,
    original_language: "th",
    original_title: "13 หมูป่า: เรื่องเล่าจากในถ้ำ",
    overview:
      "In this compelling documentary, members of the Thai youth soccer team tell their stories of getting trapped in Tham Luang Cave in 2018 — and surviving.",
    popularity: 68.902,
    poster_path: "/jQb1UjOdc2DsU4SqDebrVH8dHvC.jpg",
    release_date: "2022-10-05",
    title: "The Trapped 13: How We Survived The Thai Cave",
    video: false,
    vote_average: 7.042,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [53],
    id: 105666,
    original_language: "es",
    original_title: "La llamada del sexo",
    overview:
      "A man finds a woman that reminds him of his long lost love: his step-sister with whom he initiated his sex life. But he is married and his wife wants proof of the cheating to get a divorce.",
    popularity: 31.139,
    poster_path: "/mK8z5RWaUVDBoiagrxoF8UZQuCr.jpg",
    release_date: "1977-06-25",
    title: "The Call of Sex",
    video: false,
    vote_average: 4.643,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/uFZuaesH3fb3GYqQslLbKLA9Qjq.jpg",
    genre_ids: [16, 28, 35],
    id: 45287,
    original_language: "ja",
    original_title: "はじめの一歩 -Champion Road-",
    overview:
      "Makunouchi Ippo is the new Featherweight champion of Japan and is now ready for his first title defense. His opponent, the former Jr. Featherweight champion and a medical student, Sanada Kazuki. In addition to this feud, Sanada is being coached by Kamogawa's former rival, Hama Dankichi. What makes things worse is that Sanada works at the same hospital where Kumi is a nurse at and everybody at the hospital wants Sanada to win. Not only does Ippo have to defend his title, he has to reclaim his love.",
    popularity: 21.449,
    poster_path: "/8OEX6C9h85Hg7rtsCBKIwyrpoRh.jpg",
    release_date: "2003-06-25",
    title: "Fighting Spirit: Champion Road",
    video: false,
    vote_average: 6.7,
    vote_count: 52,
  },
  {
    adult: false,
    backdrop_path: "/afMyocyc9QHdksy5EAJW6Mm2rt4.jpg",
    genre_ids: [16, 14],
    id: 50253,
    original_language: "ja",
    original_title: "聖闘士星矢 天界編 序奏 ~overture~",
    overview:
      "After the bloody battle against Hades, the goddess Athena and her saints are still recovering when they find themselves face to face with their newest and most formidable foe: the dreadful moon goddess Artemis. Artemis replaces Athena as the earth guardian deity and takes over the Sanctuary, turning Athena's Saints into her servants.  Upon invading the Sanctuary, the Bronze Saints learn that Athena was banished by Artemis and decide to fight the moon goddess in order to rescue their true goddess and free the Earth from Artemis's ominous control.",
    popularity: 45.735,
    poster_path: "/h3z0ymRvVAFJRFg6SS8I725xoZm.jpg",
    release_date: "2004-02-14",
    title: "Saint Seiya Heaven Chapter: Overture",
    video: false,
    vote_average: 7.556,
    vote_count: 232,
  },
  {
    adult: false,
    backdrop_path: "/Ant957vTnlFwOvyLdCu0OKrPCe1.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 264419,
    original_language: "es",
    original_title: "Un gallo con muchos huevos",
    overview:
      "Toto has grown and now is a young cock. An evil rancher tricks the female owner of the ranch where they live and forces her to bet the property in a cockfight in the arena. Toto is the only option to defend their home, so he must train in just one week and win the championship of the arena.",
    popularity: 20.198,
    poster_path: "/e55ZEtyXkknzBgNmrcyTICAG3gA.jpg",
    release_date: "2015-09-04",
    title: "Huevos: Little Rooster's Egg-Cellent Adventure",
    video: false,
    vote_average: 7.015,
    vote_count: 195,
  },
  ...recommendMovies,
];
